# Database connection settings
spring.datasource.url=jdbc:postgresql://localhost:5432/burse
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate settings
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# schema
spring.jpa.properties.hibernate.default_schema=app

# admin
spring.datasource.username=postgres
spring.datasource.password=123

# client
app.datasource.client.url=jdbc:postgresql://localhost:5432/brokerage_db
app.datasource.client.driver-class-name=org.postgresql.Driver
app.datasource.client.username=client
app.datasource.client.password=123

# broker
app.datasource.broker.url=jdbc:postgresql://localhost:5432/brokerage_db
app.datasource.broker.driver-class-name=org.postgresql.Driver
app.datasource.broker.username=broker
app.datasource.broker.password=123

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000

