# Database connection properties
db.url=jdbc:postgresql://localhost:5432/trading_system
db.username=postgres
db.password=123

# Application settings
app.schema=trading
app.current_broker_id=1
app.current_client_id=1