psql -U postgres
CREATE DATABASE burce;
\c burce;
CREATE SCHEMA IF NOT EXISTS app;

CREATE USER app_user WITH PASSWORD '123';

GRANT ALL PRIVILEGES ON DATABASE burce TO app_user;

GRANT ALL PRIVILEGES ON SCHEMA app TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA app GRANT ALL PRIVILEGES ON TABLES TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA app GRANT ALL PRIVILEGES ON SEQUENCES TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA app GRANT ALL PRIVILEGES ON FUNCTIONS TO app_user;


